### ISSUE TITLE
Invalid min/max in configuration comments

### ISSUE THREAD

**Issue by LemADEC** [TeamWizardry/LibrarianLib#69] opened 2018-12-23 14:42 UTC
As of 0.9.7, the configuration file comments for mana_pool_dim_whitelist is showing invalid values for min/max/default values:
```
    # Whitelisted dimensions for mana pool generation.
    # Min: [I@12a715e6
    # Default: [I@12a715e6
    # Max: [I@12a715e6
    I:mana_pool_dim_whitelist <
        0
        -6
     >
```

**Comment by yrsegal** [comment] 2018-12-23 14:43
Duplicate of #67

**Closed as completed by yrsegal** 2018-12-23 14:43 UTC
