### ISSUE TITLE
LibrarianLib causes certain overlays from other mods to be grey

### ISSUE THREAD

**Issue by aaronhowser1** [TeamWizardry/LibrarianLib#149] opened 2020-08-11 06:11 UTC
![image](https://user-images.githubusercontent.com/15698722/89863214-485b0980-db6f-11ea-8f2b-1cc662649798.png)

![image](https://user-images.githubusercontent.com/15698722/89863278-688ac880-db6f-11ea-8af1-bb398f27b49d.png)

The first image is from [More Overlays](https://www.curseforge.com/minecraft/mc-mods/more-overlays), and the second is Chisel n Bits' tape measure.

I'm on 1.12, using `librarianlib-1.12.2-4.21`. Removing it fixes the issue.

**Comment by aaronhowser1** [comment] 2020-08-11 06:16
![image](https://user-images.githubusercontent.com/15698722/89863728-4e9db580-db70-11ea-9cd8-d38783f814c9.png)

**Comment by Bluexin** [comment] 2020-08-11 12:13
Thanks for the report, but this is a dupe of #122

**Closed as completed by Bluexin** 2020-08-11 12:13 UTC
