### ISSUE TITLE
Please help with my crash

### ISSUE THREAD

**Issue by bignose100** [TeamWizardry/LibrarianLib#33] opened 2017-04-25 00:14 UTC
Was directed here to post for help

I have been trying to update my server files to the new 1.3.2 release and am having server crashes during startup that hasnt happened with 1.2.2 and will attach my crash report. Also, i have no idea how to read the crash reports (really new to this)

[crash-2017-04-24_17.09.37-server.txt](https://github.com/TeamWizardry/LibrarianLib/files/953530/crash-2017-04-24_17.09.37-server.txt)

Hope this works....

**Comment by darkling2000** [comment] 2017-04-25 02:11
+ I am getting same thing. This in relation to the latest release of FoolCraft 1.3.2. 

I am a fresh server install direct form their server file zip. 

-----------------
[02:00:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LibrarianLib Stage 2 (librarianliblate)

Caused by: java.lang.ExceptionInInitializerError
---------------- (see https://pastebin.com/5E166rzP for full crash report) ------

**Comment by Eladkay** [comment] 2017-04-25 11:14
Relevant bit: 
.Caused by: java.lang.NullPointerException
	at com.teamwizardry.librarianlib.common.core.OwnershipHandler.<init>(OwnershipHandler.kt:27)

@yrsegal

**Comment by yrsegal** [comment] 2017-04-25 15:27
not again

**Comment by darkling2000** [comment] 2017-04-28 22:45
Looks like the bug is being tracked now in #389 and the original got closed as a dupe. But it was mentioned in 389 that it was possibly linked to the NaturalPledge mod... and if both are removed the game loads... but not sure if that helps anyone here :)

**Comment by yrsegal** [comment] 2017-04-28 22:47
Ownership handler shouldn't be related to NP, yes NP will crash but that's
a separate problem

**Comment by mcdodge34** [comment] 2017-04-28 23:18
Yup, I just did that, will wait for a new version of the mod that will probably fix this crash and I'll reinstall it once its fixed, don't need it right now anyways since I'm not a fan of Botania anyways and NaturalPledge is just an addon for Botania...

**Comment by MCEventHorizon** [comment] 2017-05-12 09:42
Hey, I noticed that this crash doesn't happen(at least server side) when foamfix is removed.

**Closed** 2018-03-01 15:16 UTC
