### ISSUE TITLE
String longer than maximum allowed

### ISSUE THREAD

**Issue by Towsty** [TeamWizardry/LibrarianLib#26] opened 2017-02-20 20:45 UTC
- [x] Make sure you've got Shadowfacts Forgelin installed.
- [x] Make sure you're not reporting something that was just fixed.
- [x] Make sure you're not using an old version of LibrarianLib.
- [x] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- [x] Make sure you're using Java 7 or greater.

After you've done so, delete this template, and proceed with your issue report.

See issue https://github.com/TeamWizardry/TMT-Refraction/issues/37

**Comment by thecodewarrior** [comment] 2017-04-24 01:07
Unless you can reproduce this with later builds, I will close this. I think it most likely is something similar to an issue I experienced when making Circuitry where the network ids were mismatched due to packet annotations not being sorted before processing and thus having indeterminate load order between client and server, and thus having inconsistent discriminators. This causes one deserializer to try to deserialize a different packet type.

**Comment by Bluexin** [comment] 2017-09-07 11:10
No feedback for a long time, and supposed fixed.

**Closed** 2017-09-07 11:09 UTC
