### ISSUE TITLE
Packet Deserialization Error

### ISSUE THREAD

**Issue by crazygmr101** [TeamWizardry/LibrarianLib#162] opened 2020-12-03 08:23 UTC
https://pastebin.com/NicJkmvB

Player can log on, move around a bit, then suddenly disconnects, no apparent reason. 

Resetting playerdata doesn't help.

Edit:
Should also mention this happens for a single person out of a dozen. We're running LibLib v4.18, minecraft 1.12.2, forge 14.23.5.2815

**Comment by thecodewarrior** [comment] 2020-12-04 02:02
That log says their client is using LibLib v4.15
```
[02:50:01] [Netty Epoll Server IO #34/INFO] [FML]: Client attempting to join with 203 mods : ...,librarianlib@4.15,...
```
If your server is running v4.18 that might be the cause of the issue.

**Comment by crazygmr101** [comment] 2020-12-06 08:05
It appears I made a mistake on the original post (oops 😅). Server is running 4.15, as are we.

![image](https://user-images.githubusercontent.com/22755628/101274863-36792400-3767-11eb-84dd-f1c7fb678f87.png)
![image](https://user-images.githubusercontent.com/22755628/101274915-83f59100-3767-11eb-9a76-f9a5a248bd8a.png)

**Comment by crazygmr101** [comment] 2020-12-16 03:58
Updated liblib, still occurs on 1.12.2 4.22
https://pastebin.com/xg8JvFxK - latest.log - server

We ended up removing it, as the mod that depended on it was removed, so we had no reason for liblib anymore - Just passing along the crash

**Comment by thecodewarrior** [comment] 2021-01-01 16:44
I'm glad you ended up resolving it, even if it was by removing LibLib. 1.12 isn't going to be receiving any more updates, so I'm closing this.

Thanks for taking the time to report it though :)

**Closed as completed by thecodewarrior** 2021-01-01 16:44 UTC
