### ISSUE TITLE
SpongeForge startup crash - MixinTargetAlreadyLoadedException

### ISSUE THREAD

**Issue by brunyman** [TeamWizardry/LibrarianLib#107] opened 2019-05-30 08:17 UTC
Hi guys,

So I discovered the issue on FTB Interactions modpack on a SpongeForge Server after modpack update from 1.6.1 to 1.7.0.

The issue is caused after we updated librarianlib from 4.15 to 4.18, I also tested with any builds above 4.15 and below 4.18 and crash started right after 4.15 builds. I tested with SpongeForge 1.12.2-2768-7.1.5 but also with latest 1.12.2-2825-7.1.6-RC3731.

You can reproduce the crash by creating a server on FTB Interactions modpack version 1.7.0 and adding any spongeforge build.

**It does not generate a crash report but crashes very early on startup, here is the error:** 
https://pastebin.com/RBRKchLe

**Full server log:**
https://pastebin.com/L2RDGmCB

Thanks, please make it work with spongeforge again.

**Comment by Bluexin** [comment] 2019-05-30 08:18
Duplicate of #77

**Closed as completed by Bluexin** 2019-05-30 08:18 UTC
